//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChuyenDe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTemporary
    {
        public int ProductId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Img { get; set; }
        public string Sesion { get; set; }
    }
}
